version: '3'
services:
  # db:
  #   container_name: db
  #   image: mysql:8.2.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: app_db
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #   volumes:
  #     - ./docker/db/data:/var/lib/mysql
  #     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
  #     - ./docker/db/sql:/docker-entrypoint-initdb.d
  #   ports:
  #     - 8001:8001
  #   command: --port 8001
  #   tty: true
  api:
    container_name: api
    # depends_on:
    #   - db
    build:
      context: ./docker/python/
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command:  uvicorn main:app --reload --host 0.0.0.0 --port 8000
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - db
  #   environment:
  #     PMA_ARBITRAY: 1
  #     PMA_HOST: db
  #     PMA_USER: root
  #     PMA_PASSWORD: root
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - /sessions